site_name: omicverse Readthedocs
repo_url: https://github.com/Starlitnightly/omicverse
site_author: "Zehua Zeng"
copyright: "Copyright &copy; 2019-2023, 112 Lab, USTB"


nav:
- Index: index.md
- Installation: Installation_guild.md
- Tutorial:
    - Bulk:
        - Different expression analysis: Tutorials-bulk/t_deg.ipynb
        - Different expression analysis with DEseq2: Tutorials-bulk/t_deseq2.ipynb
        - Protein-Protein interaction (PPI) analysis by String-db: Tutorials-bulk/t_network.ipynb
        - WGCNA (Weighted gene co-expression network analysis) analysis: Tutorials-bulk/t_wgcna.ipynb
        - TCGA database preprocess: Tutorials-bulk/t_tcga.ipynb
    - Single:
        - Preprocessing the data of scRNA-seq: Tutorials-single/t_preprocess.ipynb
        - Celltype auto annotation with SCSA: Tutorials-single/t_cellanno.ipynb
        - Celltype auto annotation with MetaTiME: Tutorials-single/t_metatime.ipynb
        - Celltype annotation migration(mapping) with TOSICA: Tutorials-single/t_tosica.ipynb
        - Trajectory Inference with VIA: Tutorials-single/t_via.ipynb
        - Trajectory Inference with VIA and scVelo: Tutorials-single/t_via_velo.ipynb
        - Pathway analysis with AUCell: Tutorials-single/t_aucell.ipynb
        - Different expression analysis in scRNA-seq: Tutorials-single/t_scdeg.ipynb
        - Batch Correction with SIMBA: Tutorials-single/t_simba.ipynb
        - Drug response predict with scDrug: Tutorials-single/t_scdrug.ipynb
        - Cell interaction with CellPhoneDB: Tutorials-single/t_cellphonedb.ipynb
        - Multi omics analysis by MOFA: Tutorials-single/t_mofa.ipynb
        - Multi omics analysis by MOFA and GLUE: Tutorials-single/t_mofa_glue.ipynb
    - Bulk2Single:
        - Bulk RNA-seq generate 'interrupted' cells to interpolate scRNA-seq: Tutorials-bulk2single/t_bulktrajblend.ipynb
        - Bulk RNA-seq to Single RNA-seq: Tutorials-bulk2single/t_bulk2single.ipynb
        - Single RNA-seq to Spatial RNA-seq: Tutorials-bulk2single/t_single2spatial.ipynb
- API documentation: api/index.md
- Release notes: Release_notes.md
- Developer guild: Developer_guild.md

  


plugins:
  - mkdocs-jupyter
  - glightbox
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/ico.png
  favicon: img/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - css/custom.css